name: Proto Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect proto changes
        run: |
          # 递归搜索当前目录及其子目录下的所有 .proto 文件
          proto_files=$(find . -type f -name "*.proto")
          
          # 输出所有的 .proto 文件
          echo "$proto_files" > proto_files.txt
          echo "Proto files found and saved to proto_files.txt"

      - name: Execute protoc command on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            cd /root/protobuf/yourdata
          
